services:
  status:
    image: gucheen/status
    env_file:
      - status.env
    volumes:
      - ./database:/home/node/app/database
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always
